In [14]:
import numpy as np

In [15]:
# Create an nd array of a specified shape full of zeroes
X = np.zeros((3,2))
print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [16]:
# Create an ndarray full of ones
X = np.ones((3,5))
print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
X has dimensions: (3, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [17]:
# Create ndarray of a specified shape that is full of any number that we want
X = np.full((3,5),5)
print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
X has dimensions: (3, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


In [18]:
# Create an identity matrix
X = np.eye(5)
print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [19]:
# Create a diagonal matrix
X = np.diag([1,5,6,7])

print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[[1 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]
X has dimensions: (4, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


In [21]:
# Create an ndarray with evenly spaced values in a given interval
# Only giving the upper bound
X = np.arange(10)

print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[0 1 2 3 4 5 6 7 8 9]
X has dimensions: (10,)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


In [22]:
# Specify lower and upper bound 
X = np.arange(4,15)

print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[ 4  5  6  7  8  9 10 11 12 13 14]
X has dimensions: (11,)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


In [24]:
# Specify lower and upper bound with a step interval

X = np.arange(4,14,3)

print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[ 4  7 10 13]
X has dimensions: (4,)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


In [25]:
# Create an ndarray using linspace by specifying the number of elements we want within a given interval

X = np.linspace(0,24,11)

print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[ 0.   2.4  4.8  7.2  9.6 12.  14.4 16.8 19.2 21.6 24. ]
X has dimensions: (11,)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [26]:
# We can also exclude the upper bound from the resulting array
X = np.linspace(0,14,20,endpoint=False)

print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[ 0.   0.7  1.4  2.1  2.8  3.5  4.2  4.9  5.6  6.3  7.   7.7  8.4  9.1
  9.8 10.5 11.2 11.9 12.6 13.3]
X has dimensions: (20,)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [27]:
# Reshape an array 
Y = np.arange(10).reshape(2,5)

print(Y)

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
Y has dimensions: (2, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [30]:
# Create a random nd array in the half open interval [0,1]
X = np.random.random([3,3])

print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[[0.16663144 0.81623465 0.341508  ]
 [0.92931043 0.31651487 0.69840942]
 [0.00611321 0.88742996 0.20983959]]
X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [32]:
# Create ndarray with random integers within a given interval
X = np.random.randint(4,10,size=(4,5))

print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[[6 7 6 5 5]
 [7 8 9 8 5]
 [7 6 9 6 7]
 [7 8 5 4 9]]
X has dimensions: (4, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


In [47]:
# Create an ndarray from a normal distribution
X = np.random.normal(0,0.1, size=(1000,1000))

print(X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

[[ 0.09236806  0.15054772 -0.08327184 ... -0.00390776 -0.01606809
   0.27733616]
 [-0.0444175  -0.06792798 -0.03710932 ... -0.01873848  0.08902207
  -0.12780978]
 [ 0.00403169  0.06307978 -0.04746714 ...  0.03938307  0.00993423
  -0.22557919]
 ...
 [ 0.01341823  0.05126129 -0.08719961 ... -0.02531608  0.01400613
   0.11794854]
 [ 0.02602127 -0.05098368 -0.11435914 ... -0.17015621  0.00063405
   0.01058028]
 [ 0.06459818 -0.099485    0.03943468 ...  0.07329376 -0.10174832
  -0.11125035]]
X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [48]:
# Printing statistical properties
print('The mean of the array is', np.mean(X))
print('The maximum value of elements in X is',X.max())
print('The minimum value of elements in X is', X.min())
print('X has', (X<0).sum(), 'negative numbers')
print('X has', (X>0).sum(), 'positive numbers')

The mean of the array is 1.7615701727218613e-05
The maximum value of elements in X is 0.5092424933573477
The minimum value of elements in X is -0.45894452322364876
X has 499620 negative numbers
X has 500380 positive numbers
