In [2]:
import numpy as np

In [ ]:
# Access elements using indexing
x = np.array([1,3,3,5,6,5])

print('x =',x,'\n')

# Accessing elements using positve indices
print('The first element in x is', x[0])
print('The second element in x is',x[1])

# Accessing elements using negative indices
print('The last element in x is', x[-1])
print('The second last element in x is',x[-2])

In [ ]:
# Modify elements in rank 1 ndarrays
x = np.array([1,3,5,4,6])

print('Original x:',x)

# Change the fourth element in the array
x[4] = 22
print('Modified x:', x)

In [ ]:
# Accessing elements from rank 2 ndarrays
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('x:',x)

# Accessing elements in x
print('The (0,0) element in x:',x[0][0])
print('The (2,1) element in x:',x[2][1])


In [ ]:
# Modifying elements in rank 2 ndarrays
x = np.arange(0,10).reshape((5,2))

print('Original x:',x)

# Modifying the element
x[2,1] = 20
print('Modified x', x)

### Adding and deleting from ndarrays


In [ ]:
# Create a rank 1 ndarray
x = np.arange(0,10)

# Create a rank 2 ndarray
Y = np.arange(0,12).reshape(3,4)

print('Original x:',x)
print('Original Y:', Y)

# Delete the first and last element of x
x = np.delete(x,[0,4])

print()
print('Modified x:',x)

# Delete the first row of Y
w = np.delete(Y,0,axis=0)
print('Modified Y with rows deleted:', w)

# Delete the first and last column of Y
w = np.delete(Y,[0,3],axis=1)
print('Modified Y with columns deleted:',w)


### Appending values to ndarrays

In [39]:
# Create a rank 1 ndarray
x = np.array([1,2,3,4,5])
print('Original x \n',x)

# Append the value 6 to x
x = np.append(x,6)
print()
print("Append 6 to x\n",x)

# Append values [7,8] to x
x = np.append(x,[7,8])

print()
print('Append 7,8 to x\n',x)

Original x 
 [1 2 3 4 5]

Append 6 to x
 [1 2 3 4 5 6]

Append 7,8 to x
 [1 2 3 4 5 6 7 8]


In [35]:
# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])

# We print Y
print()
print('Original Y = \n', Y)

# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# We append a new column containing 9 and 10 to y
q = np.append(Y, [[10],[11]], axis=1)

# We print v
print()
print('v = \n', v)

# We print q
print()
print('q = \n', q)


Original Y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3 10]
 [ 4  5  6 11]]


### Inserting values into ndarrays 

In [4]:
# Create a rank 1 ndarray
x = np.array([1,2,3,4,5])
print('Original x\n',x)

# Insert elements 7,8 after 3rd element
x = np.insert(x, 2, [7,8])
print()
print('Modified x\n',x)

Original x
 [1 2 3 4 5]

Modified x
 [1 2 7 8 3 4 5]


In [13]:
# Create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6]])
print('Original Y\n', Y)

# Insert a row between first and last elements of Y
print()
v= np.insert(Y,1,[[7,8,9]],axis=0)
print('Inserting a row in Y\n',v)

# Insert a column after first column in Y
print()
w = np.insert(Y,1,[[10],[20]], axis=1)
print('Inserting a column at index 1\n',w)

Original Y
 [[1 2 3]
 [4 5 6]]

Inserting a row in Y
 [[1 2 3]
 [7 8 9]
 [4 5 6]]

Inserting a column at index 1
 [[ 1 10 20  2  3]
 [ 4 10 20  5  6]]


### Stacking arrays

### Vertical Stacking

In [18]:
# Create a rank 1 ndarray
x = np.array([1,2])
print('x\n',x)

# Create a rank 2 ndarray
Y = np.array([[3,4],[5,6]])
print()
print('Y\n',Y)

# Stack x on top of Y
z = np.vstack((x,Y))
print()
print('Vertical stacked array z\n', z)

x
 [1 2]

Y
 [[3 4]
 [5 6]]

Vertical stacked array z
 [[1 2]
 [3 4]
 [5 6]]


### Horizontal Stacking

In [24]:
# Create a rank 1 ndarray
x = np.array([[1],[2],[3]])
print('x\n',x)

# Create a rank 2 ndarray
Y = np.array([[4,5,6],[7,8,9],[10,11,12]])
print()
print('Y\n',Y)

# Stack x on Y horizontally
w = np.hstack((x,Y))
print()
print('w\n',w)


x
 [[1]
 [2]
 [3]]

Y
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

w
 [[ 1  4  5  6]
 [ 2  7  8  9]
 [ 3 10 11 12]]
