# Slicing ndarrays

As we mentioned earlier, in addition to being able to access individual elements one at a time, NumPy provides a way to access subsets of ndarrays. This is known as slicing. Slicing is performed by combining indices with the colon : symbol inside the square brackets. In general you will come across three types of slicing:

1. ndarray\[start:end\]
2. ndarray\[start:\]
3. ndarray\[:end\]
The first method is used to select elements between the start and end indices. The second method is used to select all elements from the start index till the last index. The third method is used to select all elements from the first index till the end index. We should note that in methods one and three, the end index is excluded. We should also note that since ndarrays can be multidimensional, when doing slicing you usually have to specify a slice for each dimension of the array.

We will now see some examples of how to use the above methods to select different subsets of a rank 2 ndarray.

In [2]:
import numpy as np

## Selecting subsets of arrays

In [13]:
# Create 4*5 ndarray containing integers from 0 to 19
x = np.arange(20).reshape((4,5))
print('x\n',x)

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = x[1:4,2:5]
print('Z\n', Z)

# Selecting the same elements using method 2
w = x[1:,2:]
print('w\n',w)

# Selecting all elements in the 3rd row
v = x[2,:]
print('v\n',v)

# Selecting all elements in the 3rd column
q = x[:,2]
print('q\n',q)

# Selecting all elements in the 3rd column but returning a rank 2 ndarray
r = x[:,2:3]
print('r\n',r)
print(r.shape)

x
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Z
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
w
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
v
 [10 11 12 13 14]
q
 [ 2  7 12 17]
r
 [[ 2]
 [ 7]
 [12]
 [17]]
(4, 1)


Notice that when we selected all the elements in the 3rd column, variable q above, the slice returned a rank 1 ndarray instead of a rank 2 ndarray. However, slicing X in a slightly different way, variable R above, we can actually get a rank 2 ndarray instead.

## Arrays and Views

It is important to note that when we perform slices on ndarrays and save them into new variables, as we did above, the data is not copied into the new variable. This is one feature that often causes confusion for beginners. Therefore, we will look at this in a bit more detail.

In the above examples, when we make assignments, such as:

Z = X\[1:4,2:5\]
the slice of the original array X is not copied in the variable Z. Rather, X and Z are now just two different names for the same ndarray. We say that slicing only creates a view of the original array. This means that if you make changes in Z you will be in effect changing the elements in X as well. Let's see this with an example:

In [11]:
# We create a 4*5 ndarray that contains integers from 0 to 19

x = np.arange(0,20).reshape((4,5))
print('x:\n',x)

# We select elements that are in the 2nd to 4th rows and in the 3rd to 4th columns
Z = x[1:4,2:5]
print()
print('Z\n',Z)

# Change the last element in z to 5
Z[2][2] = 55
print()
print('Z\n',Z)

# Print x and see if it's element changed
print()
print('x\n',x)


x:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Z
 [[ 7  8  9]
 [12 13 14]
 [17 18 55]]

x
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 55]]


We can clearly see in the above example that if we make changes to Z, X changes as well.

However, if we want to create a new ndarray that contains a copy of the values in the slice we need to use the np.copy() function. The np.copy(ndarray) function creates a copy of the given ndarray. This function can also be used as a method, in the same way as we did before with the reshape function. Let's do the same example we did before but now with copies of the arrays. We'll use copy both as a function and as a method.

## Copying ndrrays

In [18]:
# Create a 4*5 ndarray that contains elements from 0 to 19

X = np.arange(20).reshape((4,5))
print('X\n',X)

# Create a copy of the slice of ndarray
Z = np.copy(X[2:,3:])
print('\nZ\n',Z)

# Create a copy of X using the copy() method
w = X[1:,3:].copy()
print('\nw\n',w)
print()

# Modify Z and check if elements of X have changed
Z[1][1] = 25
print('\nModified Z\n',Z)

# Print X and check if elements of X have changed
print('\nX\n',X)

X
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z
 [[13 14]
 [18 19]]

w
 [[ 8  9]
 [13 14]
 [18 19]]

Modified Z
 [[13 14]
 [18 25]]

X
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Using ndarrays to make slices

It is often useful to use one ndarray to make slices, select, or change elements in another ndarray. Let's see some examples:

In [30]:
# Create a 4*5 ndarray that contains elements from 0 to 19
x = np.arange(20).reshape((4,5))
print('x\n',x)

# Create indices array
indices = np.array([1,2])

# Obtain the 2nd and 3rd rows of x
w = x[indices]
print()
print('w\n',w)

# Obtain the 2nd and 3rd columns of x
v = x[:,indices]
print()
print('v\n',v)

x
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

w
 [[ 5  6  7  8  9]
 [10 11 12 13 14]]

v
 [[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]


## Using built-in functions to select specific elements in arrays

NumPy also offers built-in functions to select specific elements within ndarrays. For example, the np.diag(ndarray, k=N) function extracts the elements along the diagonal defined by N. As default is k=0, which refers to the main diagonal. Values of k > 0 are used to select elements in diagonals above the main diagonal, and values of k < 0 are used to select elements in diagonals below the main diagonal. Let's see an example:

In [34]:
# Create a 4*5 array with elements from 0 to 19
x = np.arange(20).reshape((4,5))
print('x\n',x)

# Print elements in the main diagonal of x
z = np.diagonal(x)
print('z\n',z)

# Print elements across lower diagonal of x
v = np.diagonal(x,-1)
print('v\n',v)

# Print elements across upper diagonal of x
w = np.diagonal(x,1)
print('w\n',w)

x
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
z
 [ 0  6 12 18]
v
 [ 5 11 17]
w
 [ 1  7 13 19]


## Extracting unique elements in an array

It is often useful to extract only the unique elements in an ndarray. We can find the unique elements in an ndarray by using the np.unique() function. The np.unique(ndarray) function returns the unique elements in the given ndarray, as in the example below:

In [37]:
# Create a 3*3 ndarray with repeated values
x = np.array([[1,2,3],[1,2,3],[1,2,5]])
print('x\n',x)

# Get unique values from x
w = np.unique(x)
print()
print('w\n',w)

x
 [[1 2 3]
 [1 2 3]
 [1 2 5]]

w
 [1 2 3 5]
